version: '3.3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - /pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asker
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    image: golang
    restart: always
    working_dir: /go/src
    volumes:
      - ./:/go/src:rw
      - ./pkg:/go/pkg:rw
      - ./cache:/root/.cache:rw
    entrypoint: go run hello aleksi
    ports:
      - 8082:8082

  frontend:
    image: node
    volumes:
      - ./frontend:/data:rw
    ports:
      - 8081:8081
    working_dir: /data
    entrypoint: npm start
